config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'welcome#home'
  get 'about', to: 'welcome#about'
  get 'contact', to: 'welcome#contact'
  resources :studies
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/study.rb
class Study < ApplicationRecord
 validates :programming_language, presence: true, length: {minimum: 3, maximum: 35 }
 validates :topic, presence: true, length: {minimum: 3, maximum: 35 }
 validates :source, presence: true, length: {minimum: 3, maximum: 50 }
 validates :description, presence: true
 validates :mood, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
    before_action :set_study, only: [:edit, :update, :show, :destroy]

    def index
        @studies = Study.all
    end
    
    
    def new
        @study = Study.new
    end

    def edit
    end

    def create
      #  render plain: params[:study].inspect
        @study = Study.new(study_params)
        if @study.save
            flash[:success] = "Your study was logged successfully!"
            redirect_to study_path(@study)
        else 
            render 'new'
        end
    end

    def update
        if @study.update(study_params)
            flash[:success] = "Study was successfully updated"
            redirect_to study_path(@study)
        else
            render 'edit'
        end
    end

    def show
    end

    def destroy
        @study.destroy
        flash[:danger] = "This study was successfully deleted"
        redirect_to studies_path
    end

    private

    def study_params
        params.require(:study).permit(:programming_language, :topic, :source, :description, :mood)
    end
   
    def set_study
        @study = Study.find(params[:id])
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home

    end

    def about

    end

    def contact

    end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; Study Log Created by Kateryna Strough
        </small>
    </footer>
</div>
            

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-xs-10 col-xx-offset-1">
        <% flash.each do |name, msg| %>
            <div class='alert alert-<%="#{name}" %>'>
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <%= link_to "Study Log", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href=""><a href="about">About <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=><%= link_to 'Studies', studies_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=><%= link_to 'Log a New Study', new_study_path %></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Study Log</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script src="https://kit.fontawesome.com/fed2e52857.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %> 
    <%= render 'layouts/messages' %>
    <div class = "container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any?%>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        Your study was not completed because you have 
                        <%= pluralize(obj.errors.count, "error") %>
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/studies/_form.html.erb
<%= render '/shared/errors', obj: @study %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@study, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :programming_language %>
        </div>
        <div class="col-sm-30">
          <%= f.text_field :programming_language, class: "form-control", placeholder: "Enter programming language", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :topic %>
        </div>
        <div class="col-sm-30">
          <%= f.text_field :topic, class: "form-control", placeholder: "Enter topic you studied" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :source %>
        </div>
        <div class="col-sm-30"> 
          <%= f.text_field :source, class: "form-control", placeholder: "Enter the source used" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-30"> 
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter detailed description about what you learned" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :mood %>
        </div>
        <div class="col-sm-30"> 
          <%= f.text_field :mood, class: "form-control", placeholder: "Enter how you feel today" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">  
      <%= link_to "Cancel request and return to studies", studies_path %>    
    </div>
  </div>
</div>

app/views/studies/edit.html.erb
<h1 align="center">Edit Your Study</h1>

</br><%= render 'form' %>

app/views/studies/index.html.erb
<h1 align="center">All Your Studies</h1>

<% @studies.each do |study| %><br>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="study-title">
                    <%= link_to study.programming_language, study_path(study) %>
                </div>
                <div class="study_body">
                    <strong>Topic:</strong><%= truncate(study.topic, length: 100) %>
                </div>
                 <div class="study_body">
                    <strong>Source:</strong><%= truncate(study.source, length: 100) %>
                </div>
                 <div class="study_body">
                    <strong>Description:</strong><%= truncate(study.description, length: 100) %>
                </div>
                 <div class="study_body">
                    <strong>Mood:</strong><%= truncate(study.mood, length: 100) %>
                </div>
                <div class="study-actions">
                    <%= link_to "Edit Study", edit_study_path(study), class: "btn btn-xs btn-primary" %> 
                    <%= link_to "Delete this study", study_path(study), 
                    method: :delete, data: {confirm: "Are you sure you want to delete this study?"}, 
                    class: "btn btn-xs btn-danger" %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/studies/new.html.erb
<h3>“Anyone who stops learning is old.” Henry Ford</h3>
</br><%= render 'form' %>



app/views/studies/show.html.erb
<h2 align="center"><%= @study.programming_language %></h2>
<div class="well col-xs-8 col-xs-offset-2">
    <br>
    <h4 class="description"><strong>Topic:</strong></h4>
    <%= simple_format(@study.topic) %>
    <hr>

    <h4><strong>Source:</strong></h4>
    <%= @study.source %>
    <hr>

    <h4><strong>Description:</strong></h4> 
    <%= @study.description %>
    <hr>

    <h4><strong>Mood:</strong></h4> 
    <%= @study.mood %>
    <hr>

    <div class="study-actions">
        <%= link_to "Edit Study", edit_study_path(@study), class: "btn btn-xs btn-primary" %> 
        <%= link_to "Delete this study", study_path(@study), 
            method: :delete, data: {confirm: "Are you sure you want to delete this study?"}, 
            class: "btn btn-xs btn-danger" %>
        <%= link_to "View all studies", studies_path, class: "btn btn-xs btn-success" %>
    </div>
</div>

app/views/welcome/about.html.erb
<h1>About Study Log</h1>

<p>"Progress is not achieved by luck or accident, but by working on yourself daily."~Epictetus</p>


<p>“Don't judge each day by the harvest you reap but by the seeds that you plant.” ~Robert Louis Stevenson</p>  


app/views/welcome/contact.html.erb
<h1 style="color: grey">Contact Me</h1>
<h3 style="color: light-blue">My email: katerynastrough@hotmail.com</h1>


app/views/welcome/home.html.erb
<div class="center jumbotron">
    <h1>WELCOME TO</h1>
    <h1> MY STUDY LOG</h1>
</div>

